#!/usr/bin/env bash
# PreToolUse hook: block edits to build-generated files.
#   - code.js  : the bundled goja payload, emitted from the sibling code.ts
#   - marketplace.json : regenerated from every manifest on each build
# Editing either is futile — `bun run build` overwrites it. Deny and point at the source.
# Emits a PreToolUse permission decision (deny) as JSON on stdout when matched.
set -euo pipefail

f="$(jq -r '.tool_input.file_path // empty')"
[ -z "$f" ] && exit 0

case "$f" in
  */code.js|*/marketplace.json|marketplace.json)
    jq -n --arg f "$f" '{
      hookSpecificOutput: {
        hookEventName: "PreToolUse",
        permissionDecision: "deny",
        permissionDecisionReason: ("\($f) is generated by `bun run build` — code.js is the bundled payload (edit the sibling code.ts) and marketplace.json is projected from the manifests. Edit the source and rebuild instead.")
      }
    }'
    ;;
esac
exit 0
