// Repo-local ambient declarations with no upstream goja equivalent — kept here
// so types/goja/ stays a pure mirror (regenerated by `bun run sync:types`).

// Bundle-time literal: scripts/build.ts replaces this bare identifier (via
// Bun.build `define`) with the owning extension's manifest `id`. It never
// exists at runtime — read by `getManifestId()` in src/_utils/logger.ts and by
// extension entry points / constants that use the id as a stable key. Type-only
// declaration, no emit.
declare const __MANIFEST_ID__: string;

// goja exposes a console shim; seanime does not declare it in its goja types.
interface Console {
  log(...args: unknown[]): void;
  info(...args: unknown[]): void;
  warn(...args: unknown[]): void;
  error(...args: unknown[]): void;
  debug(...args: unknown[]): void;
}
declare const console: Console;

declare namespace $store {
  function remove(key: string): void;
  function removeAll(): void;
}
